sudo: required

env: [GOSS_FILES_STRATEGY=cp, GOSS_SLEEP=15]
language: shell
services: [docker]
script:
  #
  # Don't do that as curl is already installed
  # - sudo apt-get upgrade
  # - sudo apt-get update
  # - sudo apt-get install -y --no-install-recommends curl
  #
  # Continue
  - curl -fsSL https://goss.rocks/install | sudo sh
  - ./test.sh
